name: first_workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 18
